export const ADD_ARTICLE = "ADD_ARTICLE";
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ONE_ARTICLE = "GET_ONE_ARTICLE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
